services:
  mongo:
    image: mongo
    container_name: ecommerce-mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: finalpos
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  mongo-express:
    image: mongo-express
    container_name: ecommerce-mongo-express-admin
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:finalpos@mongo:27017/ecommerce?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network
  nest-app:
    container_name: ecommerce-nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://admin:finalpos@mongo:27017/ecommerce?authSource=admin
      PORT: 3000
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecommerce-network
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
